// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJo5lMtdPFxBCudeANDC-oes-EgSORm7E',
    appId: '1:837432843375:web:eeabec30e2e4e26487c19a',
    messagingSenderId: '837432843375',
    projectId: 'fooddeliveryappflutterintro',
    authDomain: 'fooddeliveryappflutterintro.firebaseapp.com',
    storageBucket: 'fooddeliveryappflutterintro.firebasestorage.app',
    measurementId: 'G-1JSD2VRMVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWlMbTbubRa4jBDn98w0g0BLR1lqacg8',
    appId: '1:837432843375:android:0aed2331e507263d87c19a',
    messagingSenderId: '837432843375',
    projectId: 'fooddeliveryappflutterintro',
    storageBucket: 'fooddeliveryappflutterintro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXM1ZQxH_yOgScW6iOAPyOuPaCnY4bl-c',
    appId: '1:837432843375:ios:2f11cca8b1fb595887c19a',
    messagingSenderId: '837432843375',
    projectId: 'fooddeliveryappflutterintro',
    storageBucket: 'fooddeliveryappflutterintro.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXM1ZQxH_yOgScW6iOAPyOuPaCnY4bl-c',
    appId: '1:837432843375:ios:2f11cca8b1fb595887c19a',
    messagingSenderId: '837432843375',
    projectId: 'fooddeliveryappflutterintro',
    storageBucket: 'fooddeliveryappflutterintro.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJo5lMtdPFxBCudeANDC-oes-EgSORm7E',
    appId: '1:837432843375:web:2ca8639a9b596bb987c19a',
    messagingSenderId: '837432843375',
    projectId: 'fooddeliveryappflutterintro',
    authDomain: 'fooddeliveryappflutterintro.firebaseapp.com',
    storageBucket: 'fooddeliveryappflutterintro.firebasestorage.app',
    measurementId: 'G-0WYNW2QQBX',
  );
}
